### ISSUE TITLE
Did not found any category with collection name: Summer-BBQ/Hidden-Category

### ISSUE THREAD

**Issue by Tkko** [shopwareLabs/nextjs-shopware-starter#12]
I installed `Shopware` and `Nextjs` commerce projects locally but when I'm visiting the home page I get this error in logs

```
[useListing][search] Did not found any category with collection name: Summer-BBQ/Hidden-Category
[useListing][search] Did not found any category with collection name: Summer-BBQ/Hidden-Carousel-Category
```

I added categories Hidden-Category and Hidden-Carousel-Category but it still isn't working

![Screenshot 2024-03-14 at 6 31 45 PM](https://github.com/shopwareLabs/nextjs-shopware-starter/assets/26390946/6177661a-1953-4591-aa9b-d3ec4d36cbe6)

BTW the Nextjs app is running in the broswer:

<img width="434" alt="Screenshot 2024-03-14 at 6 34 10 PM" src="https://github.com/shopwareLabs/nextjs-shopware-starter/assets/26390946/1a03e823-21c8-45e8-a3a1-dac9fd468cdf">

**Comment by BrocksiNet** [comment]
Currently, it is hardcoded in:
`components/carousel.tsx`
and 
`components/grid/three-items.tsx`

You can change it to your needs:
```
  const collectionName = isSeoUrls()
    ? 'Summer-BBQ/Hidden-Carousel-Category'
    : 'ff7bf3c59f1342a685844fbf8fdf9dc8';
  const { products } = await getCollectionProducts({
    collection: collectionName
  });
```
It would be best if you matched the seoURL or the category UUID depending on whether you use seoURLs.
Check the correct seoURL in the default Storefront and copy it.
